version: '3.8'

services:
  kc-v2-api:
    build: ./api
    container_name: kc-v2-api
    ports:
      - "3333:3333"
    environment:
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    networks:
      - inetd
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kc-api.rule=Host(`api.kc.vcia.com.br`)"
      - "traefik.http.services.kc-api.loadbalancer.server.port=3333"

networks:
  inetd:
    external: true
    name: inetd